// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gktnjynalkthnwcrzmab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrdG5qeW5hbGt0aG53Y3J6bWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzI4MTgsImV4cCI6MjA3MzYwODgxOH0.jMPkujCrdIQbUIsKR0NVQctMmHHrXRdcVOb3r8cwjkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});